language: rust
rust:
  - stable

script:
  - cargo build --release
  - cargo test --release

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
      - libc++-dev
      - libc++abi-dev

before_install:
  - eval "CC=clang-5.0 && CXX=clang++-5.0"
